name: Gitee repos mirror periodic job

on:
  push:
    # delete this item if you don't want to trigger this workflow when modify this repo
    branches: master
  schedule:
    # Runs at 01:00 UTC (9:00 AM Beijing) every day
    - cron:  '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Mirror the Gitee organization repos to Github.
      uses: Yikun/hub-mirror-action@v1.0
      with:
        src: gitee/git-laiyf-net
        dst: github/laiyoufafa
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.HUB_TOKEN }}
        account_type: user
        timeout: 600
        force_update: true
        static_list: "kernel_linux_build,security_crypto_framework"
