name: Gitee repos mirror periodic job

on:
  pull_request:
    paths:
    - '.github/workflows/mirror_test.yml'
    # Runs at every pull requests submitted in master branch 
    branches: [ master ]
  schedule:
    # Runs at 01:00 UTC (9:00 AM Beijing) every day
    - cron:  '15 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Get repo and time
      id: info
      uses: actions/github-script@v3.1
      with:
        result-encoding: string
        script: |
          core.setOutput('time', new Date(Date.now()).toISOString().replace(/[^0-9]/g, ""));
          core.setOutput('key', `${context.repo.owner}-${context.repo.repo}`);
          return context.repo.repo;

    - name: Cache src repos
      uses: actions/cache@v2.1.3
      id: cache
      with:
        path: ${{ github.workspace }}/hub-mirror-cache
        key: ${{ runner.os }}-${{ steps.info.outputs.key }}-cache-${{ steps.info.outputs.time }}
        restore-keys: ${{ runner.os }}-${{ steps.info.outputs.key }}-cache-

    - name: Mirror the Gitee organization repos to Github.
      uses: Yikun/hub-mirror-action@v1.2
      with:
        src: gitee/openharmony
        dst: github/laiyoufafa
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.HUB_TOKEN }}
        src_account_type: org
        dst_account_type: user
        timeout: 600
        static_list: '${{ steps.info.outputs.result }}'
        cache_path: /github/workspace/hub-mirror-cache
        force_update: true
        debug: true
