name: Gitee repos mirror periodic job

on:
  pull_request:
    paths:
    - '.github/workflows/mirror_test.yml'
    # Runs at every pull requests submitted in master branch 
    branches: [ master ]
  schedule:
    # Runs at 01:00 UTC (9:00 AM Beijing) every day
    - cron:  '45 1,8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Mirror the Gitee organization repos to Github.
      uses: Yikun/hub-mirror-action@v1.0
      with:
        src: gitee/git-laiyf-net
        dst: github/laiyoufafa
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.HUB_TOKEN }}
        account_type: user
        timeout: 600
        debug: true

    - name: Debug repo owner
      run: |
        echo ${{ github.repository_owner }}
        echo ${{ github.actor }}
